package com.yhd.webservice.cxf.client.info;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-15T10:24:45.492+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebServiceClient(name = "person", 
                  wsdlLocation = "http://localhost:8081/hello/person?wsdl",
                  targetNamespace = "http://impl.service.server.cxf.webservice.yhd.com/") 
public class Person_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.server.cxf.webservice.yhd.com/", "person");
    public final static QName PersonServiceImpPort = new QName("http://impl.service.server.cxf.webservice.yhd.com/", "PersonServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8081/hello/person?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Person_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8081/hello/person?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Person_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Person_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Person_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Person_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Person_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Person_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImpPort")
    public PersonService getPersonServiceImpPort() {
        return super.getPort(PersonServiceImpPort, PersonService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonService
     */
    @WebEndpoint(name = "PersonServiceImpPort")
    public PersonService getPersonServiceImpPort(WebServiceFeature... features) {
        return super.getPort(PersonServiceImpPort, PersonService.class, features);
    }

}
