package com.yhd.webservice.cxf.client.info;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.8
 * 2016-11-15T10:24:45.449+08:00
 * Generated source version: 3.1.8
 * 
 */
@WebService(targetNamespace = "http://service.server.cxf.webservice.yhd.com/", name = "PersonService")
@XmlSeeAlso({ObjectFactory.class})
public interface PersonService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.server.cxf.webservice.yhd.com/", className = "com.yhd.webservice.cxf.client.info.FindAll")
    @WebMethod
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.server.cxf.webservice.yhd.com/", className = "com.yhd.webservice.cxf.client.info.FindAllResponse")
    public java.util.List<com.yhd.webservice.cxf.client.info.Person> findAll(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
